# Generated by Django 2.2.1 on 2019-06-02 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único do bloco.', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_time', models.FloatField(help_text='Tempo médio para geração de novos blocos.')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único do bloco.', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único da simulação.', primary_key=True, serialize=False)),
                ('energyCost', models.FloatField(help_text='Custo em R$/kWh.')),
                ('energyCons', models.FloatField(help_text='Gasto de energia em kW.')),
                ('blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.Blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computPower', models.FloatField(help_text='Poder computacional do minerador.')),
                ('blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.Blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(help_text='Tempo em que ocorreu o evento.')),
                ('typeOfEvent', models.IntegerField(choices=[(1, 'Adição de bloco.'), (2, 'Exclusão de bloco.')], help_text='Tipo de evento.')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Block')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Blockchain')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Blockchain'),
        ),
        migrations.AddField(
            model_name='block',
            name='userMiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.Miner'),
        ),
    ]
