# Generated by Django 2.2.3 on 2019-07-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.Block'),
        ),
        migrations.AlterField(
            model_name='event',
            name='typeOfEvent',
            field=models.IntegerField(choices=[(1, 'Adição de bloco.'), (2, 'Exclusão de bloco.'), (3, 'Inserção de minerador.'), (4, 'Exclusão de minerador.')], help_text='Tipo de evento.'),
        ),
    ]
