# Generated by Django 2.2.3 on 2019-07-01 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20190701_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='computPower',
            field=models.FloatField(help_text='Poder computacional do usuário.', null=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único da simulação.', primary_key=True, serialize=False),
        ),
    ]
