# Generated by Django 2.2.3 on 2019-07-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20190701_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='userMiner',
        ),
    ]
