# Generated by Django 2.2.3 on 2019-07-01 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_remove_block_userminer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único do bloco.', primary_key=True, serialize=False),
        ),
    ]
